version: "3.8"
services:
  ros2_drone_sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ros2_drone_sim:latest
    container_name: ros2_drone_sim
    # For GUI applications
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/root/ros2_ws/src
    # Keep container running
    command: bash
    # Enable GUI
    network_mode: host
