services:
  ros2_drone_sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ros2_drone_sim:latest
    container_name: ros2_drone_sim
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
    working_dir: /root/ros2_ws
    volumes:
      - ./src:/root/ros2_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro
    network_mode: host

